# Generated by Django 5.2.3 on 2025-07-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="nameext",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="size",
            field=models.CharField(
                choices=[
                    ("Toy", "Toy"),
                    ("Small", "Small"),
                    ("Medium", "Medium"),
                    ("Large", "Large"),
                ],
                max_length=6,
            ),
        ),
    ]
