# Generated by Django 5.2.3 on 2025-07-09 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_dog_nameext_alter_dog_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="creation_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="dog",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Adopted", "Adopted"),
                    ("Fostered", "Fostered"),
                    ("Pending", "Pending"),
                    ("Unavailable", "Unavailable"),
                    ("Inactive", "Inactive"),
                ],
                default="Available",
                max_length=12,
            ),
        ),
    ]
