# Generated by Django 5.2.3 on 2025-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dog_creation_date_alter_dog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="adoption_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
