# Generated by Django 5.2.3 on 2025-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_dog_adoption_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="update_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
