# Generated by Django 5.2.3 on 2025-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_dog_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dog_images/"),
        ),
    ]
