# Generated by Django 5.2.3 on 2025-08-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dogurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="follow_up_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Ongoing", "Ongoing"),
                    ("Resolved", "Resolved"),
                    ("Investigating", "Investigating"),
                ],
                default="Open",
                max_length=15,
            ),
        ),
    ]
