# Generated by Django 5.2.3 on 2025-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_medicalrecord_follow_up_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="last_update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
