# Generated by Django 5.2.3 on 2025-08-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_medicalrecord_last_update_date_medicalrecord_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogWalker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("onboard_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("Beginner <10 walks", "Beginner <10 walks"),
                            ("General", "General"),
                            ("Experienced", "Experienced"),
                            ("KH", "KH"),
                        ],
                        default="General",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="dog",
            name="buddy_dog1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buddy1",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="buddy_dog2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buddy2",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="buddy_dog3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buddy3",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="requires_companion_dog",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dog",
            name="walk_guidance",
            field=models.CharField(
                choices=[
                    ("Bed rest", "Bed rest"),
                    ("Less than 20 mins", "Less than 20 mins"),
                    ("Greater Than 20 mins", "Greater Than 20 mins"),
                    ("Unlimited", "Unlimited"),
                ],
                default="Greater Than 20 mins",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="walker_capability",
            field=models.CharField(
                choices=[
                    ("Beginner <10", "Beginner <10"),
                    ("General", "General"),
                    ("Experienced", "Experienced"),
                    ("KH", "KH"),
                ],
                default="General",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="DogWalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walk_date", models.DateField()),
                ("duration_minutes", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "walking_style",
                    models.CharField(
                        choices=[
                            ("Calm/loose leash", "Calm/loose leash"),
                            ("Didnt walk", "Didnt walk"),
                            ("Pulled strongly", "Pulled strongly"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "friendliness",
                    models.CharField(
                        choices=[
                            ("Aloof", "Aloof"),
                            ("Allowed patting", "Allowed patting"),
                            ("Cuddly", "Cuddly"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "buddy_dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="walkbuddy",
                        to="core.dog",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.dog"
                    ),
                ),
                (
                    "walker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.dogwalker"
                    ),
                ),
            ],
        ),
    ]
