# Generated by Django 5.2.3 on 2025-08-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_dogwalker_dog_buddy_dog1_dog_buddy_dog2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogwalker",
            name="experience",
            field=models.CharField(
                choices=[
                    ("Beginner <10 walks", "Beginner <10 walks"),
                    ("General", "General"),
                    ("Experienced", "Experienced"),
                    ("KH", "KH"),
                    ("Dog Buddy", "Dog Buddy"),
                ],
                default="General",
                max_length=25,
            ),
        ),
    ]
