# Generated by Django 5.2.3 on 2025-08-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_dogwalker_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="buddy_dog1",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="buddy_dog2",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="buddy_dog3",
        ),
        migrations.AddField(
            model_name="dog",
            name="bonded_pair_dog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bonded_pair_dog_rel",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="friend_dog1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="friend1",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="friend_dog2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="friend2",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="friend_dog3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="friend3",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="friend_dog4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="friend4",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="friend_dog5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="friend5",
                to="core.dog",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="friend_dog6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="friend6",
                to="core.dog",
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="walker_capability",
            field=models.CharField(
                choices=[
                    ("Beginner <10", "Beginner <10"),
                    ("General", "General"),
                    ("Experienced", "Experienced"),
                    ("KH", "KH"),
                    ("Dog Buddy", "Dog Buddy"),
                ],
                default="General",
                max_length=25,
            ),
        ),
    ]
