# Generated by Django 5.2.3 on 2025-08-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_dog_buddy_dog1_remove_dog_buddy_dog2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="local_created_dog",
            field=models.BooleanField(default=False),
        ),
    ]
