# Generated by Django 5.2.3 on 2025-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_dog_local_created_dog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogurl",
            name="url",
            field=models.ImageField(blank=True, null=True, upload_to="dog_images/"),
        ),
    ]
