# Generated by Django 5.2.3 on 2025-08-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_dogurl_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dogurl",
            old_name="url",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="dogurl",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.dog"
            ),
        ),
    ]
