# Generated by Django 5.2.3 on 2025-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_url_dogurl_image_alter_dogurl_dog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Adopted", "Adopted"),
                    ("Adopted-Ret", "Adopted-Ret"),
                    ("Fostered", "Fostered"),
                    ("Pending", "Pending"),
                    ("Unavailable", "Unavailable"),
                    ("Inactive", "Inactive"),
                ],
                default="Available",
                max_length=12,
            ),
        ),
    ]
