# Generated by Django 5.2.3 on 2025-08-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_dog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="friend_dog4",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="friend_dog5",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="friend_dog6",
        ),
    ]
