# Generated by Django 5.2.3 on 2025-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_dog_friend_dog4_remove_dog_friend_dog5_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogSnapshotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("created", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("deactivated", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("details", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
